# Generated by Django 4.1.7 on 2023-02-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('patronymic', models.CharField(max_length=25)),
                ('sur_name', models.CharField(max_length=25)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clients',
                'unique_together': {('first_name', 'patronymic', 'sur_name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('kit_state', models.CharField(max_length=150)),
                ('defect', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'device_types',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=25)),
                ('patronymic', models.CharField(max_length=25)),
                ('sur_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=50)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('device_type', models.ManyToManyField(to='main.devicetype')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'employee_types',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_duration', models.IntegerField()),
                ('is_visiting', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employee')),
            ],
            options={
                'db_table': 'repairs',
            },
        ),
        migrations.CreateModel(
            name='RepairStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'repair_statuses',
            },
        ),
        migrations.CreateModel(
            name='RepairType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'repair_types',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(default=None)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.client')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.device')),
                ('repair', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.repair')),
            ],
            options={
                'db_table': 'repair_orders',
            },
        ),
        migrations.AddField(
            model_name='repair',
            name='repair_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.repairtype'),
        ),
        migrations.AddField(
            model_name='repair',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.repairstatus'),
        ),
        migrations.CreateModel(
            name='EmployeeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=100)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employee')),
                ('repair_order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.repairorder')),
            ],
            options={
                'db_table': 'employee_comments',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.employeetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.devicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('model', 'serial_number')},
        ),
    ]
