# Generated by Django 4.1.7 on 2023-02-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sur_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='sur_name',
            new_name='last_name',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('first_name', 'patronymic', 'last_name', 'phone')},
        ),
    ]
